import type { Metadata, Viewport } from 'next';
import '@/styles/globals.scss';
import { Navigation } from '@/widgets/menu-navigation';

import { Inter } from 'next/font/google';
import Script from 'next/script';
import { Providers } from './Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	maximumScale: 1,
	userScalable: false
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='ru'
			suppressHydrationWarning
		>
			<body className={inter.className}>
				<Providers>
					<Script
						src='https://telegram.org/js/telegram-web-app.js'
						strategy='beforeInteractive'
					/>
					{children}
					<Navigation />
				</Providers>
			</body>
		</html>
	);
}
